# Base URL for the API
@baseUrl = http://localhost:8080/api

# Authentication Endpoints

### Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "username",
  "password": "password123",
  "email" : "rouinedexplorer@gmail.com",
  "role": "Employee"
}

### Login a user
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin" 
}

# // newuser password123
# Resignation Endpoints

### Submit a resignation request
POST {{baseUrl}}/resignations/submit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2JiN2M0NTBlMDc4MTJlMmNlYWRmNzgiLCJpYXQiOjE3NDAzNDAyOTZ9.-9UxtEztVaR4ZC1iLL1jiAy7AIWhI7Izdr08Y80Pf3o

{
  "intendedLastWorkingDay": "2023-12-04",
  "reason": "Personal reasons"
}

### see all resignation request
GET {{baseUrl}}/resignations/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2JiN2JkYzBlMDc4MTJlMmNlYWRmNzMiLCJpYXQiOjE3NDAzNDE4MDF9.HfKkL6Gq8MAPsrgTttk2xEKG-KwwVVslnWNXbI67cAg


### Review a resignation request
PUT {{baseUrl}}/resignations/review/67bb7f250efc14ba4d13f3b7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2JiN2JkYzBlMDc4MTJlMmNlYWRmNzMiLCJpYXQiOjE3NDAzNDE4MDF9.HfKkL6Gq8MAPsrgTttk2xEKG-KwwVVslnWNXbI67cAg

{
  "status": "Approved",
  "exitDate": "2023-12-31"
}

# Exit Interview Endpoints

### Submit an exit interview
POST {{baseUrl}}/exit-interviews/submit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2JiN2M0NTBlMDc4MTJlMmNlYWRmNzgiLCJpYXQiOjE3NDAzNDAyOTZ9.-9UxtEztVaR4ZC1iLL1jiAy7AIWhI7Izdr08Y80Pf3o

{
  "questions": ["Why are you leaving?"],
  "answers": ["Better opportunity"]
}

### Get all exit interviews
GET {{baseUrl}}/exit-interviews/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2JiN2JkYzBlMDc4MTJlMmNlYWRmNzMiLCJpYXQiOjE3NDAzNDE4MDF9.HfKkL6Gq8MAPsrgTttk2xEKG-KwwVVslnWNXbI67cAg
